package com.foreveross.webbase.solidchoice.dao;

import com.senson.entity.IntegralConfig;
import com.senson.entity.IntegralConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntegralConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int countByExample(IntegralConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int deleteByExample(IntegralConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int insert(IntegralConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int insertSelective(IntegralConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    List<IntegralConfig> selectByExample(IntegralConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    IntegralConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") IntegralConfig record, @Param("example") IntegralConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int updateByExample(@Param("record") IntegralConfig record, @Param("example") IntegralConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int updateByPrimaryKeySelective(IntegralConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_integral_config
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    int updateByPrimaryKey(IntegralConfig record);
}