package com.foreveross.webbase.solidchoice.entity;

import java.util.Date;

public class IntegralLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_level.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_level.integral_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long integralId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_level.intgral
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long intgral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_level.level
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_level.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_level.id
     *
     * @return the value of a_integral_level.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_level.id
     *
     * @param id the value for a_integral_level.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_level.integral_id
     *
     * @return the value of a_integral_level.integral_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getIntegralId() {
        return integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_level.integral_id
     *
     * @param integralId the value for a_integral_level.integral_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIntegralId(Long integralId) {
        this.integralId = integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_level.intgral
     *
     * @return the value of a_integral_level.intgral
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getIntgral() {
        return intgral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_level.intgral
     *
     * @param intgral the value for a_integral_level.intgral
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIntgral(Long intgral) {
        this.intgral = intgral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_level.level
     *
     * @return the value of a_integral_level.level
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_level.level
     *
     * @param level the value for a_integral_level.level
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_level.create_time
     *
     * @return the value of a_integral_level.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_level.create_time
     *
     * @param createTime the value for a_integral_level.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}