package com.foreveross.webbase.solidchoice.entity;

import java.util.Date;

public class IntegralRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.user_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.operation_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.type_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.note
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.capital
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer capital;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.integral_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer integralType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_integral_record.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.id
     *
     * @return the value of a_integral_record.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.id
     *
     * @param id the value for a_integral_record.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.user_id
     *
     * @return the value of a_integral_record.user_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.user_id
     *
     * @param userId the value for a_integral_record.user_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.operation_type
     *
     * @return the value of a_integral_record.operation_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.operation_type
     *
     * @param operationType the value for a_integral_record.operation_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.type_id
     *
     * @return the value of a_integral_record.type_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.type_id
     *
     * @param typeId the value for a_integral_record.type_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.note
     *
     * @return the value of a_integral_record.note
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.note
     *
     * @param note the value for a_integral_record.note
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.capital
     *
     * @return the value of a_integral_record.capital
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.capital
     *
     * @param capital the value for a_integral_record.capital
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setCapital(Integer capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.integral_type
     *
     * @return the value of a_integral_record.integral_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getIntegralType() {
        return integralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.integral_type
     *
     * @param integralType the value for a_integral_record.integral_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIntegralType(Integer integralType) {
        this.integralType = integralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_integral_record.create_time
     *
     * @return the value of a_integral_record.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_integral_record.create_time
     *
     * @param createTime the value for a_integral_record.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}