package com.foreveross.webbase.solidchoice.entity;

import java.util.Date;

public class VoteIntegralDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.topic_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.user_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.vote_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer voteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.is_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer isLike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.is_attention
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer isAttention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.amount
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.intergral_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer intergralType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.remark
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_vote_integral_detail.is_del
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.id
     *
     * @return the value of a_vote_integral_detail.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.id
     *
     * @param id the value for a_vote_integral_detail.id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.topic_id
     *
     * @return the value of a_vote_integral_detail.topic_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.topic_id
     *
     * @param topicId the value for a_vote_integral_detail.topic_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.user_id
     *
     * @return the value of a_vote_integral_detail.user_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.user_id
     *
     * @param userId the value for a_vote_integral_detail.user_id
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.vote_type
     *
     * @return the value of a_vote_integral_detail.vote_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getVoteType() {
        return voteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.vote_type
     *
     * @param voteType the value for a_vote_integral_detail.vote_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setVoteType(Integer voteType) {
        this.voteType = voteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.is_like
     *
     * @return the value of a_vote_integral_detail.is_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getIsLike() {
        return isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.is_like
     *
     * @param isLike the value for a_vote_integral_detail.is_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIsLike(Integer isLike) {
        this.isLike = isLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.is_attention
     *
     * @return the value of a_vote_integral_detail.is_attention
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getIsAttention() {
        return isAttention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.is_attention
     *
     * @param isAttention the value for a_vote_integral_detail.is_attention
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIsAttention(Integer isAttention) {
        this.isAttention = isAttention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.amount
     *
     * @return the value of a_vote_integral_detail.amount
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.amount
     *
     * @param amount the value for a_vote_integral_detail.amount
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.intergral_type
     *
     * @return the value of a_vote_integral_detail.intergral_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getIntergralType() {
        return intergralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.intergral_type
     *
     * @param intergralType the value for a_vote_integral_detail.intergral_type
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIntergralType(Integer intergralType) {
        this.intergralType = intergralType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.remark
     *
     * @return the value of a_vote_integral_detail.remark
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.remark
     *
     * @param remark the value for a_vote_integral_detail.remark
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.create_time
     *
     * @return the value of a_vote_integral_detail.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.create_time
     *
     * @param createTime the value for a_vote_integral_detail.create_time
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_vote_integral_detail.is_del
     *
     * @return the value of a_vote_integral_detail.is_del
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_vote_integral_detail.is_del
     *
     * @param isDel the value for a_vote_integral_detail.is_del
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}