package com.foreveross.webbase.solidchoice.entity;

import com.foreveross.webbase.common.persistence.DataEntity;

import java.util.Date;

public class Topic  extends DataEntity<Topic> {

    private String id;

    private String userId;

    private String topicName;

    private Integer topicType;

    private String topicLabel;

    private Integer releaseForm;

    private String note;

    private Integer status;

    private String address;

    private String activityRules;

    private String integralMechanism;

    private Integer isRecommend;

    private Date recommendTime;

    private Integer participants;

    private String imgUrl;

    private Integer isDel;

    private Date createTime;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.user_id
     *
     * @param userId the value for a_topic.user_id
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.topic_name
     *
     * @return the value of a_topic.topic_name
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.topic_name
     *
     * @param topicName the value for a_topic.topic_name
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.topic_type
     *
     * @return the value of a_topic.topic_type
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getTopicType() {
        return topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.topic_type
     *
     * @param topicType the value for a_topic.topic_type
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setTopicType(Integer topicType) {
        this.topicType = topicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.topic_label
     *
     * @return the value of a_topic.topic_label
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getTopicLabel() {
        return topicLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.topic_label
     *
     * @param topicLabel the value for a_topic.topic_label
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setTopicLabel(String topicLabel) {
        this.topicLabel = topicLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.release_form
     *
     * @return the value of a_topic.release_form
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getReleaseForm() {
        return releaseForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.release_form
     *
     * @param releaseForm the value for a_topic.release_form
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setReleaseForm(Integer releaseForm) {
        this.releaseForm = releaseForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.note
     *
     * @return the value of a_topic.note
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.note
     *
     * @param note the value for a_topic.note
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.status
     *
     * @return the value of a_topic.status
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.status
     *
     * @param status the value for a_topic.status
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.address
     *
     * @return the value of a_topic.address
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.address
     *
     * @param address the value for a_topic.address
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.activity_rules
     *
     * @return the value of a_topic.activity_rules
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getActivityRules() {
        return activityRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.activity_rules
     *
     * @param activityRules the value for a_topic.activity_rules
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setActivityRules(String activityRules) {
        this.activityRules = activityRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.integral_mechanism
     *
     * @return the value of a_topic.integral_mechanism
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getIntegralMechanism() {
        return integralMechanism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.integral_mechanism
     *
     * @param integralMechanism the value for a_topic.integral_mechanism
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setIntegralMechanism(String integralMechanism) {
        this.integralMechanism = integralMechanism;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.is_recommend
     *
     * @return the value of a_topic.is_recommend
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getIsRecommend() {
        return isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.is_recommend
     *
     * @param isRecommend the value for a_topic.is_recommend
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setIsRecommend(Integer isRecommend) {
        this.isRecommend = isRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.recommend_time
     *
     * @return the value of a_topic.recommend_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Date getRecommendTime() {
        return recommendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.recommend_time
     *
     * @param recommendTime the value for a_topic.recommend_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setRecommendTime(Date recommendTime) {
        this.recommendTime = recommendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.participants
     *
     * @return the value of a_topic.participants
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getParticipants() {
        return participants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.participants
     *
     * @param participants the value for a_topic.participants
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setParticipants(Integer participants) {
        this.participants = participants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.img_url
     *
     * @return the value of a_topic.img_url
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.img_url
     *
     * @param imgUrl the value for a_topic.img_url
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.is_del
     *
     * @return the value of a_topic.is_del
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.is_del
     *
     * @param isDel the value for a_topic.is_del
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic.create_time
     *
     * @return the value of a_topic.create_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic.create_time
     *
     * @param createTime the value for a_topic.create_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}