package com.foreveross.webbase.solidchoice.entity;

import java.util.Date;

public class TopicDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.is_disable
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Integer isDisable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.is_del
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.update_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long updateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.update_name
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.update_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.create_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.create_name
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_topic_details.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.id
     *
     * @return the value of a_topic_details.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.id
     *
     * @param id the value for a_topic_details.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.is_disable
     *
     * @return the value of a_topic_details.is_disable
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Integer getIsDisable() {
        return isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.is_disable
     *
     * @param isDisable the value for a_topic_details.is_disable
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setIsDisable(Integer isDisable) {
        this.isDisable = isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.is_del
     *
     * @return the value of a_topic_details.is_del
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.is_del
     *
     * @param isDel the value for a_topic_details.is_del
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.update_uid
     *
     * @return the value of a_topic_details.update_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.update_uid
     *
     * @param updateUid the value for a_topic_details.update_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setUpdateUid(Long updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.update_name
     *
     * @return the value of a_topic_details.update_name
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.update_name
     *
     * @param updateName the value for a_topic_details.update_name
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.update_time
     *
     * @return the value of a_topic_details.update_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.update_time
     *
     * @param updateTime the value for a_topic_details.update_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.create_uid
     *
     * @return the value of a_topic_details.create_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.create_uid
     *
     * @param createUid the value for a_topic_details.create_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.create_name
     *
     * @return the value of a_topic_details.create_name
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.create_name
     *
     * @param createName the value for a_topic_details.create_name
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_topic_details.create_time
     *
     * @return the value of a_topic_details.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_topic_details.create_time
     *
     * @param createTime the value for a_topic_details.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}