package com.foreveross.webbase.solidchoice.entity;

import com.foreveross.webbase.common.persistence.DataEntity;

import java.util.Date;

public class VipUser extends DataEntity<VipUser> {
    private String phone;

    private String testCode;

    private String email;

    private String nickName;

    private String jobTitle;

    private Integer level;

    private String name;

    private String intro;

    private String password;

    private Integer gender;

    private String userType;

    private String mobileVer;

    private String phoneModel;

    private String operatingSystem;

    private String systemVer;

    private String openId;

    private Integer userStatus;

    private String token;

    private Integer isMember;

    private String avatarPath;

    private String backgroundPath;

    private String birthData;

    private String remarks;

    private Date lastLoginTime;

    private String area;

    private Integer isDisable;

    private Integer isDel;

    private Date updateTime;

    private Date createTime;

    private String label;

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getTestCode() {
        return testCode;
    }

    public void setTestCode(String testCode) {
        this.testCode = testCode;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getJobTitle() {
        return jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.user_type
     *
     * @param userType the value for a_user.user_type
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.mobile_ver
     *
     * @return the value of a_user.mobile_ver
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getMobileVer() {
        return mobileVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.mobile_ver
     *
     * @param mobileVer the value for a_user.mobile_ver
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setMobileVer(String mobileVer) {
        this.mobileVer = mobileVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.phone_model
     *
     * @return the value of a_user.phone_model
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getPhoneModel() {
        return phoneModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.phone_model
     *
     * @param phoneModel the value for a_user.phone_model
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setPhoneModel(String phoneModel) {
        this.phoneModel = phoneModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.operating_system
     *
     * @return the value of a_user.operating_system
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.operating_system
     *
     * @param operatingSystem the value for a_user.operating_system
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setOperatingSystem(String operatingSystem) {
        this.operatingSystem = operatingSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.system_ver
     *
     * @return the value of a_user.system_ver
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getSystemVer() {
        return systemVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.system_ver
     *
     * @param systemVer the value for a_user.system_ver
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setSystemVer(String systemVer) {
        this.systemVer = systemVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.open_id
     *
     * @return the value of a_user.open_id
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.open_id
     *
     * @param openId the value for a_user.open_id
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }


    public Integer getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.token
     *
     * @param token the value for a_user.token
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.is_member
     *
     * @return the value of a_user.is_member
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getIsMember() {
        return isMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.is_member
     *
     * @param isMember the value for a_user.is_member
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setIsMember(Integer isMember) {
        this.isMember = isMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.avatar_path
     *
     * @return the value of a_user.avatar_path
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getAvatarPath() {
        return avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.avatar_path
     *
     * @param avatarPath the value for a_user.avatar_path
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.background_path
     *
     * @return the value of a_user.background_path
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getBackgroundPath() {
        return backgroundPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.background_path
     *
     * @param backgroundPath the value for a_user.background_path
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setBackgroundPath(String backgroundPath) {
        this.backgroundPath = backgroundPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.birth_data
     *
     * @return the value of a_user.birth_data
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getBirthData() {
        return birthData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.birth_data
     *
     * @param birthData the value for a_user.birth_data
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setBirthData(String birthData) {
        this.birthData = birthData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.remarks
     *
     * @return the value of a_user.remarks
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.remarks
     *
     * @param remarks the value for a_user.remarks
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.last_login_time
     *
     * @return the value of a_user.last_login_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.last_login_time
     *
     * @param lastLoginTime the value for a_user.last_login_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.area
     *
     * @return the value of a_user.area
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.area
     *
     * @param area the value for a_user.area
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.is_disable
     *
     * @return the value of a_user.is_disable
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getIsDisable() {
        return isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.is_disable
     *
     * @param isDisable the value for a_user.is_disable
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setIsDisable(Integer isDisable) {
        this.isDisable = isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.is_del
     *
     * @return the value of a_user.is_del
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.is_del
     *
     * @param isDel the value for a_user.is_del
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.update_time
     *
     * @return the value of a_user.update_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.update_time
     *
     * @param updateTime the value for a_user.update_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.create_time
     *
     * @return the value of a_user.create_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.create_time
     *
     * @param createTime the value for a_user.create_time
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_user.label
     *
     * @return the value of a_user.label
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_user.label
     *
     * @param label the value for a_user.label
     *
     * @mbggenerated Thu Sep 06 18:24:28 CST 2018
     */
    public void setLabel(String label) {
        this.label = label;
    }
}