package com.foreveross.webbase.solidchoice.entity;

import com.foreveross.webbase.common.persistence.DataEntity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Created by HIAPAD on 2018/9/10.
 */
public class Voting extends DataEntity<Voting>{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_banner.text
     *
     * @mbggenerated Mon Sep 10 17:47 CST 2018
     */
    private String topicId; //话题id

    private Integer supports;//支持人数

    private Integer opposes;//反对人数

    private BigDecimal winIntegrals;//赢取积分数

    private Integer currentRank;//当前排名

    private Integer comments;//活动中的评论数
    
    private Date createTime;//创建时间
    
    private int checkStaus; //审核状态 0 未审核 1 审核通过 2 审核不通过

    private Topic topic; //话题对象
    
    private List<TopicComment> comment;//话题对象
    
    public int getCheckStaus() {
		return checkStaus;
	}

	public void setCheckStaus(int checkStaus) {
		this.checkStaus = checkStaus;
	}

	public Topic getTopic() {
		return topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public List<TopicComment> getComment() {
		return comment;
	}

	public void setComment(List<TopicComment> comment) {
		this.comment = comment;
	}

	public String getTopicId() {
		return topicId;
	}

	public void setTopicId(String topicId) {
		this.topicId = topicId;
	}

	public Integer getSupports() {
        return supports;
    }

    public void setSupports(Integer supports) {
        this.supports = supports;
    }

    public Integer getOpposes() {
        return opposes;
    }

    public void setOpposes(Integer opposes) {
        this.opposes = opposes;
    }


    public BigDecimal getWinIntegrals() {
		return winIntegrals;
	}

	public void setWinIntegrals(BigDecimal winIntegrals) {
		this.winIntegrals = winIntegrals;
	}

	public Integer getCurrentRank() {
		return currentRank;
	}

	public void setCurrentRank(Integer currentRank) {
		this.currentRank = currentRank;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getComments() {
        return comments;
    }

    public void setComments(Integer comments) {
        this.comments = comments;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }
}
