package com.foreveross.webbase.solidchoice.dao;

import com.foreveross.webbase.solidchoice.entity.Like;
import com.foreveross.webbase.solidchoice.entity.LikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int countByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int deleteByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int insertSelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    List<Like> selectByExample(LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    Like selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByExample(@Param("record") Like record, @Param("example") LikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByPrimaryKeySelective(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_like
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByPrimaryKey(Like record);
}