package com.foreveross.webbase.solidchoice.dao;

import com.foreveross.webbase.solidchoice.entity.UserUnion;
import com.foreveross.webbase.solidchoice.entity.UserUnionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserUnionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int countByExample(UserUnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int deleteByExample(UserUnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int insert(UserUnion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int insertSelective(UserUnion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    List<UserUnion> selectByExample(UserUnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    UserUnion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserUnion record, @Param("example") UserUnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByExample(@Param("record") UserUnion record, @Param("example") UserUnionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByPrimaryKeySelective(UserUnion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_user_union
     *
     * @mbggenerated Thu Sep 06 10:11:00 CST 2018
     */
    int updateByPrimaryKey(UserUnion record);
}