package com.senson.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_comment.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_comment.topic_id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long topicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_comment.com_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long comUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_comment.content
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_comment.imgs
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String imgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_comment.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_comment.id
     *
     * @return the value of a_comment.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_comment.id
     *
     * @param id the value for a_comment.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_comment.topic_id
     *
     * @return the value of a_comment.topic_id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_comment.topic_id
     *
     * @param topicId the value for a_comment.topic_id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_comment.com_uid
     *
     * @return the value of a_comment.com_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getComUid() {
        return comUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_comment.com_uid
     *
     * @param comUid the value for a_comment.com_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setComUid(Long comUid) {
        this.comUid = comUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_comment.content
     *
     * @return the value of a_comment.content
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_comment.content
     *
     * @param content the value for a_comment.content
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_comment.imgs
     *
     * @return the value of a_comment.imgs
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_comment.imgs
     *
     * @param imgs the value for a_comment.imgs
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_comment.create_time
     *
     * @return the value of a_comment.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_comment.create_time
     *
     * @param createTime the value for a_comment.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}