package com.senson.entity;

import java.util.Date;

public class DictionaryType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.type
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.description
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.is_disable
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Integer isDisable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.update_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long updateUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.update_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.create_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Long createUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_dictionary_type.is_del
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.id
     *
     * @return the value of a_dictionary_type.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.id
     *
     * @param id the value for a_dictionary_type.id
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.type
     *
     * @return the value of a_dictionary_type.type
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.type
     *
     * @param type the value for a_dictionary_type.type
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.description
     *
     * @return the value of a_dictionary_type.description
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.description
     *
     * @param description the value for a_dictionary_type.description
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.is_disable
     *
     * @return the value of a_dictionary_type.is_disable
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Integer getIsDisable() {
        return isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.is_disable
     *
     * @param isDisable the value for a_dictionary_type.is_disable
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setIsDisable(Integer isDisable) {
        this.isDisable = isDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.update_uid
     *
     * @return the value of a_dictionary_type.update_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.update_uid
     *
     * @param updateUid the value for a_dictionary_type.update_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setUpdateUid(Long updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.update_time
     *
     * @return the value of a_dictionary_type.update_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.update_time
     *
     * @param updateTime the value for a_dictionary_type.update_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.create_uid
     *
     * @return the value of a_dictionary_type.create_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Long getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.create_uid
     *
     * @param createUid the value for a_dictionary_type.create_uid
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setCreateUid(Long createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.create_time
     *
     * @return the value of a_dictionary_type.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.create_time
     *
     * @param createTime the value for a_dictionary_type.create_time
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_dictionary_type.is_del
     *
     * @return the value of a_dictionary_type.is_del
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_dictionary_type.is_del
     *
     * @param isDel the value for a_dictionary_type.is_del
     *
     * @mbggenerated Wed Sep 05 18:05:14 CST 2018
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}